# Generated by Django 3.1 on 2020-09-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200907_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='default slug', unique=True),
            preserve_default=False,
        ),
    ]
