# Generated by Django 3.1 on 2020-08-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('timestamp',)},
        ),
    ]
