# Generated by Django 3.1 on 2020-08-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['timestamp', 'updated']},
        ),
    ]
